# Generated by Django 5.0.3 on 2024-03-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='campaign',
        ),
    ]
